// ================================================================
//  BETTER EDIT TOOLS – Sandboxels Mod
//  Replaces worldEdit.js with a multi‑slot clipboard, portal
//  autofill, and mobile‑friendly paste mode.
// ================================================================

(function () {
  'use strict';

  // ──────────────────────────────────── Rect class (from worldEdit.js) ─
  class Rect {
    constructor(x, y, w, h) {
      this.x = x; this.y = y; this.w = w; this.h = h;
    }
    static fromCorners(start, end) {
      return new Rect(start.x, start.y, end.x - start.x, end.y - start.y);
    }
    static fromCornersXYXY(x, y, x2, y2) {
      return new Rect(x, y, x2 - x, y2 - y);
    }
    static fromGrid(grid, origin = { x: 0, y: 0 }) {
      return new Rect(origin.x, origin.y, grid[0].length, grid.length);
    }
    get area() { return this.w * this.h; }
    get x2() { return this.x + this.w; }
    get y2() { return this.y + this.h; }
    set x2(val) { this.w = val - this.x; }
    set y2(val) { this.h = val - this.y; }
    copy() { return new Rect(this.x, this.y, this.w, this.h); }
    normalized() {
      return Rect.fromCornersXYXY(
        Math.min(this.x, this.x2), Math.min(this.y, this.y2),
        Math.max(this.x, this.x2), Math.max(this.y, this.y2)
      );
    }
  }

  // ──────────────────────────────────── Helpers ─────────────────────
  const isPointInWorld = (p) => p.x >= 0 && p.x <= width && p.y >= 0 && p.y <= height;
  const limitPointToWorld = (p) => ({
    x: Math.max(0, Math.min(p.x, width)),
    y: Math.max(0, Math.min(p.y, height))
  });

  // Get canvas‑relative grid coordinates, respecting zoom.js and MMM
  function mousePosToWorldPos(clientX, clientY) {
    if (typeof window.mmm_locked !== 'undefined' && window.mmm_locked) {
      // mobileMouse1.js is active – use its virtual cursor
      return { x: window.mmm_cursor.x, y: window.mmm_cursor.y };
    }
    const evt = { clientX, clientY };
    // zoom.js replaces getMousePos; always call the game’s own version
    return getMousePos(canvas, evt);
  }

  // Deep clone a pixel (all enumerable own properties except x, y)
  function clonePixel(pixel) {
    if (!pixel) return null;
    const clone = {};
    for (const key in pixel) {
      if (key === 'x' || key === 'y') continue;
      const val = pixel[key];
      // simple deep copy for objects/arrays that we may have (e.g. color arrays)
      if (typeof val === 'object' && val !== null) {
        clone[key] = JSON.parse(JSON.stringify(val));
      } else {
        clone[key] = val;
      }
    }
    return clone;
  }

  // ──────────────────────────────────── State ───────────────────────
  const state = {
    selection: null,            // Rect or null
    clipboard: [],              // [ { name, data (2D array of pixel clones) } ]
    slotIndex: -1,              // visually selected slot (for paste/rename)
    pasteMode: false,
    pasteSlot: -1,              // index in clipboard to preview/paste
    pasteAnchor: null,          // {x, y} where preview is anchored
    pasteAnchorSet: false,      // true once first click anchors
    autofillSlots: [],          // temporary slots generated by autofill
    autofillIndex: 0,
    panelOpen: false,
    selecting: false,           // dragging a new selection
    firstSelPos: null,
    lastNonEditElement: null,   // for fill button
    transformCache: null        // { grid, width, height } for current paste slot
  };

  // ──────────────────────────────────── Clipboard Slot Helpers ─────
  function addSlot(name, data) {
    state.clipboard.push({ name, data });
    state.slotIndex = state.clipboard.length - 1;
    renderSlots();
  }

  function deleteSlot(index) {
    state.clipboard.splice(index, 1);
    if (state.slotIndex >= state.clipboard.length) state.slotIndex = state.clipboard.length - 1;
    if (state.pasteSlot === index) { cancelPasteMode(); }
    else if (state.pasteSlot > index) state.pasteSlot--;
    renderSlots();
  }

  function renameSlot(index, newName) {
    state.clipboard[index].name = newName;
    renderSlots();
  }

  function duplicateSlot(index) {
    const orig = state.clipboard[index];
    const newData = orig.data.map(row => row.map(p => p ? clonePixel(p) : null));
    addSlot(orig.name + ' (copy)', newData);
  }

  function clearSlotData(index) {
    state.clipboard[index].data = [];
    renderSlots();
  }

  function moveSlotUp(index) {
    if (index === 0) return;
    [state.clipboard[index - 1], state.clipboard[index]] = [state.clipboard[index], state.clipboard[index - 1]];
    if (state.slotIndex === index) state.slotIndex = index - 1;
    else if (state.slotIndex === index - 1) state.slotIndex = index;
    renderSlots();
  }

  function moveSlotDown(index) {
    if (index >= state.clipboard.length - 1) return;
    [state.clipboard[index], state.clipboard[index + 1]] = [state.clipboard[index + 1], state.clipboard[index]];
    if (state.slotIndex === index) state.slotIndex = index + 1;
    else if (state.slotIndex === index + 1) state.slotIndex = index;
    renderSlots();
  }

  // Transformations on a raw grid (2D array of pixel clones)
  function rotateGrid90(grid) {
    const h = grid.length, w = grid[0].length;
    const newGrid = [];
    for (let y = 0; y < w; y++) {
      const row = [];
      for (let x = 0; x < h; x++) {
        row.push(grid[h - 1 - x][y]); // rotate clockwise 90°
      }
      newGrid.push(row);
    }
    return newGrid;
  }

  function flipGridHorizontally(grid) {
    return grid.map(row => row.slice().reverse());
  }

  function flipGridVertically(grid) {
    return grid.slice().reverse();
  }

  // Get the transformed grid for the current paste slot (cached)
  function getTransformedSlot(slotIndex) {
    if (slotIndex < 0 || slotIndex >= state.clipboard.length) return null;
    const slot = state.clipboard[slotIndex];
    if (!slot.data || slot.data.length === 0) return null;
    let grid = slot.data;
    if (slot.rotate) {
      for (let i = 0; i < (slot.rotate % 4); i++) grid = rotateGrid90(grid);
    }
    if (slot.flipX) grid = flipGridHorizontally(grid);
    if (slot.flipY) grid = flipGridVertically(grid);
    return { grid, w: grid[0].length, h: grid.length };
  }

  // Cache the transformed grid when slot/transform changes
  function updateTransformCache() {
    state.transformCache = getTransformedSlot(state.pasteSlot);
  }

  // ──────────────────────────────────── Selection Rendering ─────────
  function renderSelection(ctx) {
    if (!state.selection) return;
    const r = state.selection;
    const ps = pixelSize;
    ctx.fillStyle = 'rgba(120,255,98,0.15)';
    ctx.fillRect(r.x * ps, r.y * ps, r.w * ps, r.h * ps);
    ctx.strokeStyle = '#7cff62';
    ctx.lineWidth = 1;
    ctx.setLineDash([ps, ps]);
    ctx.strokeRect(r.x * ps, r.y * ps, r.w * ps, r.h * ps);
    ctx.setLineDash([]);
  }

  // Paste preview for click‑to‑confirm
  function renderPastePreview(ctx) {
    if (!state.pasteMode || !state.transformCache) return;
    const { grid, w, h } = state.transformCache;
    const anchor = state.pasteAnchorSet ? state.pasteAnchor : mousePos; // follow mouse if not anchored
    if (!anchor) return;
    const ps = pixelSize;
    ctx.globalAlpha = 0.7;
    for (let y = 0; y < h; y++) {
      for (let x = 0; x < w; x++) {
        const pix = grid[y][x];
        if (!pix) continue;
        const drawX = (anchor.x + x) * ps;
        const drawY = (anchor.y + y) * ps;
        ctx.fillStyle = pix.color || '#ffffff';
        ctx.fillRect(drawX, drawY, ps, ps);
      }
    }
    ctx.globalAlpha = 1;

    // Draw anchor crosshair when anchored
    if (state.pasteAnchorSet && state.pasteAnchor) {
      const ax = (state.pasteAnchor.x + 0.5) * ps;
      const ay = (state.pasteAnchor.y + 0.5) * ps;
      ctx.strokeStyle = '#00ffff';
      ctx.lineWidth = 1;
      ctx.beginPath();
      ctx.moveTo(ax - ps, ay);
      ctx.lineTo(ax + ps, ay);
      ctx.moveTo(ax, ay - ps);
      ctx.lineTo(ax, ay + ps);
      ctx.stroke();
    }
  }

  // Render hook – called every frame after game pixels
  renderPostPixel((ctx) => {
    renderSelection(ctx);
    renderPastePreview(ctx);
  });

  // ──────────────────────────────────── Canvas Interaction ─────────
  function onMouseDown(e) {
    // Only left button / first touch, and not on UI
    if (e.button !== 0 && e.pointerType !== 'touch') return;
    if (e.target !== canvas && e.target.id !== 'game') return;

    if (state.pasteMode) {
      e.stopImmediatePropagation(); e.preventDefault();
      const pos = mousePosToWorldPos(e.clientX, e.clientY);
      if (!state.pasteAnchorSet) {
        state.pasteAnchor = pos;
        state.pasteAnchorSet = true;
      } else {
        const dx = Math.abs(state.pasteAnchor.x - pos.x);
        const dy = Math.abs(state.pasteAnchor.y - pos.y);
        if (dx <= 1 && dy <= 1) {
          // Confirm paste at the anchor
          pasteFromSlot(state.pasteSlot, state.pasteAnchor);
          cancelPasteMode();
        } else {
          // Reposition anchor
          state.pasteAnchor = pos;
        }
      }
      return;
    }

    if (state.selecting) {
      const pos = mousePosToWorldPos(e.clientX, e.clientY);
      if (!isPointInWorld(pos)) return;
      state.firstSelPos = pos;
      state.selection = null;
      e.stopImmediatePropagation(); e.preventDefault();
    }
  }

  function onMouseMove(e) {
    if (!state.selecting || !mouseIsDown) return;
    const pos = mousePosToWorldPos(e.clientX, e.clientY);
    const start = state.firstSelPos;
    if (!start) return;
    const end = limitPointToWorld(pos);
    const rect = Rect.fromCorners(start, end).normalized();
    rect.x2 += 1; rect.y2 += 1;
    state.selection = rect;
  }

  function onMouseUp(e) {
    if (state.selecting) state.selecting = false;
  }

  // Attach listeners (capture phase to beat game)
  function installListeners() {
    canvas.addEventListener('pointerdown', onMouseDown, { capture: true, passive: false });
    canvas.addEventListener('pointermove', onMouseMove, { capture: false });
    canvas.addEventListener('pointerup', onMouseUp);
    // Also block game default when selection mode active
    canvas.addEventListener('mousedown', (e) => { if (state.selecting || state.pasteMode) e.stopImmediatePropagation(); }, { capture: true });
    canvas.addEventListener('touchstart', (e) => { if (state.selecting || state.pasteMode) e.stopImmediatePropagation(); }, { capture: true });
  }

  // ──────────────────────────────────── Operations ─────────────────
  function doSelectAll() {
    state.selection = new Rect(0, 0, width + 1, height + 1);
  }

  function doDeselect() {
    state.selection = null;
  }

  function doCopy(toNewSlot = true) {
    if (!state.selection) return;
    const r = state.selection;
    const grid = [];
    for (let y = r.y; y < r.y2; y++) {
      const row = [];
      for (let x = r.x; x < r.x2; x++) {
        const pixel = pixelMap[x]?.[y];
        row.push(pixel ? clonePixel(pixel) : null);
      }
      grid.push(row);
    }
    if (toNewSlot) {
      const name = 'Slot ' + (state.clipboard.length + 1);
      addSlot(name, grid);
    } else {
      // Overwrite current slot
      if (state.slotIndex >= 0) {
        state.clipboard[state.slotIndex].data = grid;
      } else {
        addSlot('Slot 1', grid);
      }
      renderSlots();
    }
  }

  function doCut() {
    if (!state.selection) return;
    const r = state.selection;
    const grid = [];
    for (let y = r.y; y < r.y2; y++) {
      const row = [];
      for (let x = r.x; x < r.x2; x++) {
        const pixel = pixelMap[x]?.[y];
        row.push(pixel ? clonePixel(pixel) : null);
        if (pixel) deletePixel(x, y);
      }
      grid.push(row);
    }
    addSlot('Slot ' + (state.clipboard.length + 1), grid);
    state.selection = null;
  }

  function doDelete() {
    if (!state.selection) return;
    const r = state.selection;
    for (let y = r.y; y < r.y2; y++) {
      for (let x = r.x; x < r.x2; x++) {
        if (pixelMap[x]?.[y]) deletePixel(x, y);
      }
    }
    state.selection = null;
  }

  function doFill() {
    if (!state.selection) return;
    const r = state.selection;
    const fillElem = state.lastNonEditElement || currentElement;
    if (!fillElem || fillElem === 'unknown') return;
    for (let y = r.y; y < r.y2; y++) {
      for (let x = r.x; x < r.x2; x++) {
        if (!pixelMap[x]?.[y]) {
          createPixel(fillElem, x, y);
        }
      }
    }
    state.selection = null;
  }

  // Paste a slot at the given anchor (top-left)
  function pasteFromSlot(slotIndex, anchor) {
    const transformed = getTransformedSlot(slotIndex);
    if (!transformed) return;
    const { grid, w, h } = transformed;
    for (let y = 0; y < h; y++) {
      for (let x = 0; x < w; x++) {
        const pix = grid[y][x];
        if (!pix) continue;
        const dx = anchor.x + x, dy = anchor.y + y;
        if (!isPointInWorld({ x: dx, y: dy })) continue;
        if (pixelMap[dx]?.[dy]) continue; // don't overwrite
        createPixel(pix.element, dx, dy);
        const newPixel = pixelMap[dx][dy];
        if (newPixel) {
          // Copy all saved properties
          for (const key in pix) {
            if (key === 'element' || key === 'x' || key === 'y') continue;
            newPixel[key] = (typeof pix[key] === 'object' && pix[key] !== null)
              ? JSON.parse(JSON.stringify(pix[key]))
              : pix[key];
          }
          // Re‑initialize start time
          newPixel.start = pixelTicks;
        }
      }
    }
  }

  function cancelPasteMode() {
    state.pasteMode = false;
    state.pasteSlot = -1;
    state.pasteAnchorSet = false;
    state.transformCache = null;
  }

  function startPasteMode(slotIndex) {
    if (slotIndex < 0 || slotIndex >= state.clipboard.length) return;
    state.pasteMode = true;
    state.pasteSlot = slotIndex;
    state.pasteAnchorSet = false;
    updateTransformCache();
  }

  // ──────────────────────────────────── Autofill Portals ───────────
  // Compare two slot grids and generate new slots with incremented portal channels
  function autofillPortals(slotIndexA, slotIndexB) {
    if (slotIndexA < 0 || slotIndexB < 0 || slotIndexA === slotIndexB) return;
    const gridA = state.clipboard[slotIndexA].data;
    const gridB = state.clipboard[slotIndexB].data;
    if (!gridA || !gridB || gridA.length !== gridB.length || gridA[0].length !== gridB[0].length) {
      logMessage('[BET] Slots must have the same dimensions to autofill portals.');
      return;
    }

    const h = gridA.length, w = gridA[0].length;
    let increment = null;
    const portalPairs = []; // {x, y, type, chA, chB}

    for (let y = 0; y < h; y++) {
      for (let x = 0; x < w; x++) {
        const pixA = gridA[y]?.[x];
        const pixB = gridB[y]?.[x];
        if (!pixA && !pixB) continue;
        // One side has a portal but the other doesn't -> abort
        if ((pixA && pixA.element === 'portal_in' || pixA && pixA.element === 'portal_out') !==
            (pixB && pixB.element === 'portal_in' || pixB && pixB.element === 'portal_out')) {
          logMessage('[BET] Slot mismatch at ('+x+','+y+'): portal presence differs.');
          return;
        }
        if (pixA && (pixA.element === 'portal_in' || pixA.element === 'portal_out')) {
          const chA = parseInt(pixA.channel) || 0;
          const chB = parseInt(pixB.channel) || 0;
          if (increment === null) {
            increment = chB - chA;
          } else if (chB - chA !== increment) {
            logMessage('[BET] Inconsistent channel difference at ('+x+','+y+'). Expected '+increment+' but got '+(chB-chA));
            return;
          }
          portalPairs.push({ x, y, type: pixA.element, chA, chB });
        } else {
          // Non‑portal pixel: both must be completely equal
          if (JSON.stringify(pixA) !== JSON.stringify(pixB)) {
            logMessage('[BET] Non‑portal pixel mismatch at ('+x+','+y+').');
            return;
          }
        }
      }
    }

    if (increment === 0) {
      logMessage('[BET] The two slots have identical portal channels – nothing to fill.');
      return;
    }

    // Generate next 5 slots
    const generated = [];
    for (let i = 1; i <= 5; i++) {
      const newGrid = gridB.map(row => row.map(pixel => pixel ? clonePixel(pixel) : null));
      for (const pp of portalPairs) {
        const pix = newGrid[pp.y][pp.x];
        if (pix) pix.channel = (pp.chB + increment * i).toString();
      }
      generated.push({ name: 'Autofill ' + i, data: newGrid });
    }

    state.autofillSlots = generated;
    state.autofillIndex = 0;
    renderSlots(); // will show new autofill section
    logMessage('[BET] Generated 5 autofill slots with channel increment ' + increment + '.');
  }

  function pasteNextAutofill() {
    if (state.autofillSlots.length === 0) return;
    const slot = state.autofillSlots[state.autofillIndex];
    // Temporarily add to clipboard for paste preview
    const tmpIndex = state.clipboard.length;
    addSlot(slot.name, slot.data);
    startPasteMode(tmpIndex);
    // Remove temporary slot after paste is confirmed (or cancelled)
    // We'll set a callback for paste completion
    state._autofillCleanup = () => {
      deleteSlot(tmpIndex);
      state.autofillIndex++;
      if (state.autofillIndex >= state.autofillSlots.length) {
        state.autofillSlots = [];
        state.autofillIndex = 0;
      }
      renderSlots();
    };
  }

  // Override paste confirmation to call cleanup for autofill
  const originalPasteFromSlot = pasteFromSlot;
  window._BET_pasteFromSlot = function(slotIndex, anchor) {
    originalPasteFromSlot(slotIndex, anchor);
    if (state._autofillCleanup) {
      state._autofillCleanup();
      state._autofillCleanup = null;
    }
    cancelPasteMode();
  };

  // Actually paste from slot (wrapped)
  pasteFromSlot = (slotIndex, anchor) => {
    window._BET_pasteFromSlot(slotIndex, anchor);
  };

  // ──────────────────────────────────── Export / Import ────────────
  function exportSlots() {
    const data = state.clipboard.map(s => ({ name: s.name, data: s.data }));
    const json = JSON.stringify(data);
    const blob = new Blob([json], { type: 'application/json' });
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = 'betterEditSlots.json';
    a.click();
  }

  function importSlots() {
    const input = document.createElement('input');
    input.type = 'file';
    input.accept = '.json';
    input.addEventListener('change', (e) => {
      const file = e.target.files[0];
      if (!file) return;
      const reader = new FileReader();
      reader.onload = (ev) => {
        let imported;
        try { imported = JSON.parse(ev.target.result); } catch (err) {
          logMessage('[BET] Invalid JSON file.'); return;
        }
        if (!Array.isArray(imported)) {
          logMessage('[BET] Import must be an array of slots.'); return;
        }
        state.clipboard = imported.map(s => ({ name: s.name || 'Imported', data: s.data || [] }));
        state.slotIndex = -1;
        cancelPasteMode();
        renderSlots();
      };
      reader.readAsText(file);
    });
    input.click();
  }

  // ──────────────────────────────────── UI Building ─────────────────
  let panelElements = {};

  function buildPanel() {
    // Styles injected once
    if (document.getElementById('bet-styles')) return;
    const style = document.createElement('style');
    style.id = 'bet-styles';
    style.textContent = `
      #bet-panel {
        position: fixed; bottom: 0; left: 50%; transform: translateX(-50%);
        width: 90vw; max-width: 500px; max-height: 60vh;
        background: rgba(0,0,0,0.92); border: 2px solid #7cff62;
        border-radius: 10px 10px 0 0; z-index: 10000;
        display: flex; flex-direction: column; color: #ccc;
        font-family: monospace; font-size: 12px;
        overflow-y: auto; resize: both; padding: 8px;
        user-select: none; -webkit-user-select: none;
      }
      .bet-row { display: flex; align-items: center; gap: 4px; margin: 2px 0; }
      .bet-btn {
        background: #1a1a1a; color: #7cff62; border: 1px solid #444;
        border-radius: 3px; padding: 3px 6px; font-size: 11px;
        cursor: pointer; touch-action: manipulation;
      }
      .bet-btn:active { background: #2a2a2a; }
      .bet-slot-name { flex: 1; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; padding: 0 4px; }
      .bet-section { border-top: 1px solid #333; margin-top: 6px; padding-top: 4px; }
    `;
    document.head.appendChild(style);

    const panel = document.createElement('div');
    panel.id = 'bet-panel';
    panel.style.display = 'none';
    panel.innerHTML = `
      <div class="bet-row">
        <button class="bet-btn" id="bet-btn-select">🔲 Select</button>
        <button class="bet-btn" id="bet-btn-deselect">❌ Deselect</button>
        <button class="bet-btn" id="bet-btn-selectall">⬜ All</button>
        <button class="bet-btn" id="bet-btn-copy">📋 Copy</button>
        <button class="bet-btn" id="bet-btn-cut">✂️ Cut</button>
        <button class="bet-btn" id="bet-btn-delete">🗑 Delete</button>
        <button class="bet-btn" id="bet-btn-fill">🧱 Fill</button>
      </div>
      <div class="bet-section" id="bet-paste-row" style="display: none;">
        <button class="bet-btn" id="bet-btn-paste">📌 Paste</button>
        <span id="bet-paste-name" style="margin-left:6px;"></span>
        <button class="bet-btn" id="bet-btn-rot90">↻90°</button>
        <button class="bet-btn" id="bet-btn-flipX">↔ X</button>
        <button class="bet-btn" id="bet-btn-flipY">↕ Y</button>
        <button class="bet-btn" id="bet-btn-cancel">✕ Cancel</button>
      </div>
      <div class="bet-section">
        <div style="font-weight:bold;">Slots</div>
        <div id="bet-slot-list"></div>
        <div class="bet-row">
          <button class="bet-btn" id="bet-btn-export">📤 Export</button>
          <button class="bet-btn" id="bet-btn-import">📥 Import</button>
        </div>
      </div>
      <div class="bet-section" id="bet-autofill-section" style="display:none;">
        <div style="font-weight:bold;">Autofill Portals</div>
        <div class="bet-row">
          <select id="bet-autofill-selA"></select>
          <span>vs</span>
          <select id="bet-autofill-selB"></select>
          <button class="bet-btn" id="bet-btn-autofill">▶ Generate</button>
        </div>
        <div id="bet-autofill-next-container" style="display:none; margin-top:4px;">
          <button class="bet-btn" id="bet-btn-autofill-next">+ Autofill Next</button>
        </div>
      </div>
    `;
    document.body.appendChild(panel);
    panelElements.panel = panel;
    panelElements.pasteRow = panel.querySelector('#bet-paste-row');
    panelElements.slotList = panel.querySelector('#bet-slot-list');
    panelElements.autofillSection = panel.querySelector('#bet-autofill-section');
    panelElements.autofillSelA = panel.querySelector('#bet-autofill-selA');
    panelElements.autofillSelB = panel.querySelector('#bet-autofill-selB');
    panelElements.autofillNextContainer = panel.querySelector('#bet-autofill-next-container');
  }

  function renderSlots() {
    if (!panelElements.slotList) return;
    panelElements.slotList.innerHTML = '';
    state.clipboard.forEach((slot, index) => {
      const row = document.createElement('div');
      row.className = 'bet-row';
      row.style.background = index === state.slotIndex ? '#2a2a2a' : 'transparent';
      row.innerHTML = `
        <span class="bet-slot-name">${slot.name}</span>
        <button class="bet-btn bet-slot-sel" data-idx="${index}">📋</button>
        <button class="bet-btn bet-slot-dup" data-idx="${index}">📄</button>
        <button class="bet-btn bet-slot-clr" data-idx="${index}">🧹</button>
        <button class="bet-btn bet-slot-del" data-idx="${index}">🗑</button>
        <button class="bet-btn bet-slot-rename" data-idx="${index}">✏️</button>
        <button class="bet-btn bet-slot-up" data-idx="${index}">▲</button>
        <button class="bet-btn bet-slot-down" data-idx="${index}">▼</button>
      `;
      panelElements.slotList.appendChild(row);
    });

    // Populate autofill selectors
    if (panelElements.autofillSelA) {
      panelElements.autofillSelA.innerHTML = state.clipboard.map((s, i) => `<option value="${i}">${s.name}</option>`).join('');
      panelElements.autofillSelB.innerHTML = panelElements.autofillSelA.innerHTML;
    }
    if (state.autofillSlots.length > 0) {
      panelElements.autofillNextContainer.style.display = 'block';
    } else {
      panelElements.autofillNextContainer.style.display = 'none';
    }
  }

  function attachUIEvents() {
    // Panel toggle button (in toolbar)
    const toolbar = document.getElementById('toolControls');
    if (!toolbar) return;
    const btn = document.createElement('button');
    btn.id = 'bet-edit-btn';
    btn.textContent = '🛠️ Edit';
    btn.title = 'Better Edit Tools';
    btn.style.cssText = 'background:none; border:none; cursor:pointer; font-size:18px; opacity:0.85;';
    btn.addEventListener('click', () => {
      state.panelOpen = !state.panelOpen;
      if (state.panelOpen) {
        panelElements.panel.style.display = 'block';
        state.lastNonEditElement = currentElement;
      } else {
        panelElements.panel.style.display = 'none';
        cancelPasteMode();
        state.selecting = false;
      }
      renderSlots();
    });
    toolbar.appendChild(btn);

    // Event delegation from the panel
    panelElements.panel.addEventListener('click', (e) => {
      const t = e.target;
      if (t.id === 'bet-btn-select') {
        state.selecting = true;
      } else if (t.id === 'bet-btn-deselect') {
        doDeselect();
      } else if (t.id === 'bet-btn-selectall') {
        doSelectAll();
      } else if (t.id === 'bet-btn-copy') {
        doCopy(true);
      } else if (t.id === 'bet-btn-cut') {
        doCut();
      } else if (t.id === 'bet-btn-delete') {
        doDelete();
      } else if (t.id === 'bet-btn-fill') {
        doFill();
      } else if (t.id === 'bet-btn-paste') {
        if (state.slotIndex >= 0) startPasteMode(state.slotIndex);
      } else if (t.id === 'bet-btn-cancel') {
        cancelPasteMode();
      } else if (t.id === 'bet-btn-rot90') {
        if (state.pasteSlot >= 0) {
          const s = state.clipboard[state.pasteSlot];
          s.rotate = ((s.rotate || 0) + 1) % 4;
          updateTransformCache();
        }
      } else if (t.id === 'bet-btn-flipX') {
        if (state.pasteSlot >= 0) {
          const s = state.clipboard[state.pasteSlot];
          s.flipX = !s.flipX;
          updateTransformCache();
        }
      } else if (t.id === 'bet-btn-flipY') {
        if (state.pasteSlot >= 0) {
          const s = state.clipboard[state.pasteSlot];
          s.flipY = !s.flipY;
          updateTransformCache();
        }
      } else if (t.id === 'bet-btn-export') {
        exportSlots();
      } else if (t.id === 'bet-btn-import') {
        importSlots();
      } else if (t.id === 'bet-btn-autofill') {
        const a = parseInt(panelElements.autofillSelA.value);
        const b = parseInt(panelElements.autofillSelB.value);
        autofillPortals(a, b);
        renderSlots();
      } else if (t.id === 'bet-btn-autofill-next') {
        pasteNextAutofill();
      } else {
        // Slot row buttons
        const idx = parseInt(t.getAttribute('data-idx'));
        if (isNaN(idx)) return;
        if (t.classList.contains('bet-slot-sel')) {
          state.slotIndex = idx;
          renderSlots();
        } else if (t.classList.contains('bet-slot-dup')) {
          duplicateSlot(idx);
        } else if (t.classList.contains('bet-slot-clr')) {
          clearSlotData(idx);
        } else if (t.classList.contains('bet-slot-del')) {
          deleteSlot(idx);
        } else if (t.classList.contains('bet-slot-rename')) {
          promptInput('New name:', (name) => { if (name) renameSlot(idx, name); }, 'Rename Slot');
        } else if (t.classList.contains('bet-slot-up')) {
          moveSlotUp(idx);
        } else if (t.classList.contains('bet-slot-down')) {
          moveSlotDown(idx);
        }
      }
    });
  }

  // ──────────────────────────────────── Keybinds ────────────────────
  function addKeybinds() {
    keybinds['w'] = () => {
      document.getElementById('bet-edit-btn')?.click(); // toggle panel
    };
    keybinds['s'] = () => {
      state.selecting = !state.selecting;
      if (state.selecting) state.pasteMode = false;
    };
    keybinds['c'] = () => doCopy(true);
    keybinds['v'] = () => {
      if (state.slotIndex >= 0) startPasteMode(state.slotIndex);
    };
    keybinds['x'] = () => doCut();
    keybinds['d'] = () => doDeselect();
    keybinds['a'] = () => doSelectAll();
    keybinds['g'] = () => doFill();
    keybinds['Delete'] = () => doDelete();
    keybinds['Backspace'] = () => doDelete(); // also Delete
  }

  // ──────────────────────────────────── Initialisation ──────────────
  function init() {
    if (typeof pixelMap === 'undefined' || !document.getElementById('toolControls')) {
      setTimeout(init, 200);
      return;
    }
    buildPanel();
    attachUIEvents();
    installListeners();
    addKeybinds();

    // Patch runAfterReset so we clean up state
    runAfterReset(() => {
      state.selection = null;
      cancelPasteMode();
      state.selecting = false;
    });

    console.log('[BET] Better Edit Tools loaded.');
  }

  init();
})();